// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVmuZhWbm2s11ietsmJi32v48v8RrBGn8',
    appId: '1:87823477764:web:228ace26f5a6cd8117d951',
    messagingSenderId: '87823477764',
    projectId: 'social-app-1-9cb08',
    authDomain: 'social-app-1-9cb08.firebaseapp.com',
    storageBucket: 'social-app-1-9cb08.firebasestorage.app',
    measurementId: 'G-BSHXR6MZXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsM_EMqE6QzmpWFccmL9tGm9awhCbz7RM',
    appId: '1:87823477764:android:a2fba2dac5a8548117d951',
    messagingSenderId: '87823477764',
    projectId: 'social-app-1-9cb08',
    storageBucket: 'social-app-1-9cb08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYK-_zP8n3bUjJuyPVt3vshRT6_MX1cqQ',
    appId: '1:87823477764:ios:634a742ec7c0ec1417d951',
    messagingSenderId: '87823477764',
    projectId: 'social-app-1-9cb08',
    storageBucket: 'social-app-1-9cb08.firebasestorage.app',
    iosBundleId: 'com.example.socialApp1',
  );

}